baseurl = "amitkohli.com"
title = "AmitKohli.com"
theme = "ghostwriter"
languageCode = "en-us"
copyright = "My Name"
disqusShortname = "amitkohli-com"
googleAnalytics = "UA-39057488-1"
ignoreFiles = ["\\.Rmd$", "\\.Rmarkdown$", "_files$", "_cache$"]

[Privacy]

[Privacy.disqus]
    disable = true

[Privacy.googleAnalytics]
    anonymizeIP = true
    respectDoNotTrack = true
    useSessionStorage = false

[Author]
    name = "Amit"
    profile = "https://www.linkedin.com/in/akohli"

[Taxonomies]
    tag = "tags"
    category = "categories"

[Params]
    intro = true
    headline = "AmitKohli.com"
    description = "... because I can and I want to and you can't stop me."
    github = "https://github.com/datastrategist"
    linkedin = "https://www.linkedin.com/in/akohli"
    twitter = "https://twitter.com/VizMonkey"
    stackoverflow = "https://stackoverflow.com/users/2883603/amit-kohli"
    opengraph = true
    shareTwitter = true
    shareFacebook = true
    shareGooglePlus = true
    shareLinkedIn = true
    dateFormat = "Mon, Jan 2, 2006"
    highlightJsUrl = ""
    highlightJsLocalUrl = ""

[Permalinks]
    post = "/:year/:month/:day/:filename/"

[[menu.main]]
    name = "Blog"
    url = "/"
    weight = 1

[[menu.main]]
    name = "Projects"
    url = "/project/"
    weight = 2
    
[[menu.main]]
    name = "Categories"
    url = "/categories/"
    weight = 3

[[menu.main]]
    name = "About"
    url = "/page/about/"
    weight = 4
