---
title: Crime Statistics in London
author: Amit
date: '2018-07-07'
slug: crime-statistics-in-london
categories: [Data,R]
tags: []
description: ''
output: html_document
draft: no
---

Blah blah




```{r setup, include=FALSE}
library(tidyverse)
library(leaflet)
```

Load in the data:
```{r warning=FALSE}
### Digest London crime data and create a visual by neighbourhood
FileNames <- list.files(path = "../data/LondonCrime",recursive = T, full.names = T)

df <- FileNames %>% map_dfr(read.csv)

df_large <- df
names(df)

df <- df_large %>%
  select(Longitude,Latitude,Crime.type)
```


First Map:
```{r}
leaflet(data = head(df)) %>%
  addTiles() %>%
  addMarkers(lng = ~Longitude, lat = ~Latitude)
```

Truncate ds to London only:

```{r}
df <- df %>% 
  filter(Latitude < 51.715036,
         Latitude > 51.282286,
         Longitude < 0.296875,
         Longitude > -0.527704)
```

Create tiles for London

```{r}
df <- df %>% 
  mutate(LatDelta = round((Latitude  - min(Latitude))/.2,1)) %>% 
  mutate(LongDelta = round((Longitude  - min(Longitude))/.2,1)) %>% 
  mutate(UID = paste0(LatDelta,"|", LongDelta))
  
df %>% head
```

How much crime per UID?
```{r}
UIDCrimes <- df %>% 
  select(UID,Crime.type) %>%
  group_by(UID, Crime.type) %>%
  summarize(n = n())
```

What's the average amount of crime per thingie:
```{r}
AveCr <- UIDCrimes %>%
  group_by(Crime.type) %>% select(-UID) %>%
  summarize(AveCrime = mean(n))
  

```


Normalize Crime amount per UID
```{r}
NormCrime <- UIDCrimes %>% 
  left_join(AveCr, by = "Crime.type") %>%
  mutate(NormalizedCrime = n - AveCrime) %>%
  select(-n, -AveCrime) %>%  
  group_by(UID) %>%
  mutate(MaxC = max(NormalizedCrime)) %>%
  filter(NormalizedCrime == MaxC) %>% 
  select(-MaxC)

NormCrime %>% head
  
```

Add back in the Mean Lat & Long
```{r}
PlotDF <- df %>%
  group_by(UID) %>%
  summarize(AveLong = mean(Longitude),
            AveLat = mean(Latitude)) %>%
  full_join(NormCrime,by = "UID") %>%
  mutate(N2Crime = scale(NormalizedCrime)) %>%
  mutate(N2Crime = N2Crime - min(N2Crime)) %>%
  mutate(N2Crimelog = log(N2Crime)) %>%
  mutate(Crime.typeBR = gsub(" ","<br>",Crime.type)) %>%
  mutate(Crime.type2 = Crime.typeBR %>% as.factor)

head(PlotDF)

# PlotDF$N2Crime %>% plot
```


Now plot these:
```{r}
pal <- colorFactor(c("red", "green", "blue"),domain = unique(PlotDF$Crime.type2))

leaflet(PlotDF) %>%
  addTiles() %>%
  addCircleMarkers(lng = ~AveLong, lat = ~AveLat,fillColor = ~pal(Crime.type2), stroke = FALSE, fillOpacity = ~N2Crimelog,
                   label = lapply(PlotDF$Crime.typeBR, htmltools::HTML)) %>% #  labelOptions = labelOptions(permanent = TRUE)
  addLegend("topright", pal = pal, values = ~Crime.typeBR,
    title = "Crime Type",
    opacity = 1
  )

#   addCircleMarkers(lng = ~AveLong, lat = ~AveLat,fillColor = ~pal(Crime.type2), stroke = FALSE, label = lapply(PlotDF$Crime.type, htmltools::HTML))
#   
# addLabelOnlyMarkers(~AveLong, ~AveLat, label =  lapply(PlotDF$Crime.type, htmltools::HTML),#~as.character(Crime.type),    
#                       labelOptions = labelOptions(style = "color:red", noHide = T, direction = 'center', opacity = ~N2Crime, textOnly = T))

```


